### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by kalouantonis** [johan-sports/wscelery#5]
Is there anyone at @johan-sports (@deniskulicek, @dsnipe, @matyasfodor, @jellereichert) maintaining this project?

If its no longer used, could it be transferred to someone who is willing to do it? I'm the original author so I'll do it if no one else picks it up.

**Comment by kalouantonis** [comment]
@

**Comment by matyasfodor** [comment]
@kalouantonis I don't

**Comment by jellereichert** [comment]
We are not maintaining this anymore, because we don't use it anymore. You are free to pick it up of course!

**Comment by kalouantonis** [comment]
@jellereichert I don't have write access because I'm not part of your organization anymore (understandably). Could you organize someone to transfer it to my account?

**Comment by matyasfodor** [comment]
@kalouantonis do you have any metrics about how many people use it?

**Comment by kalouantonis** [comment]
Well, we've already got 76 stars, 4 forks and one user submitted issue. We come up top on the search results for "websocket celery" (duckduckgo). I can't see the other statistics because I don't have access to that part of the "Insights" page.

**Comment by dsnipe** [comment]
@kalouantonis you can fork it and continue. And we can add a link to your repository in the Readme. It's a quite common practice as far as I know.

**Comment by kalouantonis** [comment]
@dsnipe Sure, that's also fine. I appreciate your help.

**Comment by kalouantonis** [comment]
I would like to note however that the package is on PyPI under the johan-sports organization. PyPI does not have namespacing so I can't submit an updated version of the package without your help.

If I submit a PR with changes would someone be willing to sort that out?

**Comment by dsnipe** [comment]
@kalouantonis sure, just assign me as a reviewer.
